import org.apache.hadoop.io.SecureIOUtils.AlreadyExistsException;
public class FunctionUse7685 {
public void funcUse() {
AlreadyExistsException alreadyexistsexception = new AlreadyExistsException();
}
}